### ISSUE TITLE
please document hash types and benchmarks for JtR

### ISSUE THREAD

**Issue by roycewilliams** [parallella/parallella-examples#18]
Could the output for JtR's benchmark (john --test) for all currently supported hash types be added to the readme or the wiki?  

This would help users evaluate whether this work will fit their requirements.

**Comment by hbfs** [comment]
Theres a  presentation with all the info and more: http://www.openwall.com/presentations/Passwords13-Energy-Efficient-Cracking/Passwords13-Energy-Efficient-Cracking.pdf

**Comment by roycewilliams** [comment]
Good enough - closing

**Comment by solardiz** [comment]
I doubt anyone cares at this time, but FWIW:

> Theres a presentation with all the info and more

This linked to the 2013 revision of it, whereas the Zynq 7020 design had since been improved. Here's 2014: https://www.openwall.com/presentations/Passwords14-Energy-Efficient-Cracking/
